#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale /home/user/Изображения/Wallpapers/274.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor primary -d 1 2 3 4 5 6 7
bspc monitor LVDS-1 -d 7  # TODO: multiple monitors

bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width         5
bspc config window_gap          17

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# start xresources
xrdb merge ~/.Xresources

# autostart
flameshot &
polybar &
picom --vsync &

# TODO: Add loading of basic scripts
~/.config/bspwm/scripts/launch.sh &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
setxkbmap -option grp:caps_toggle us,ru
